### ISSUE TITLE
Trello reports github auth error

### ISSUE THREAD

**Issue by juliawildmoka** [goodybag/trello-to-github#17]
Hello,
Ciould you please advise on the cause and fix for the following error: 
Scenario: I have just installed the plugin and restarted Chrome.
                From Trello card i specify the Github repo, title and description.
                When i click Submit button i get the popup(screenshot attached) with "github auth error" 
                message.
Chrome version: Version 48.0.2564.82 m
![image](https://cloud.githubusercontent.com/assets/16668322/12584653/cf039256-c448-11e5-8474-2f89a53c409c.png)
Thank you in advance,
Julia

**Comment by jrf0110** [comment]
Hi, @juliawildmoka -

This library is no longer maintained. I suspect that some underlying api's from github or trello have changed significantly since the creation of the extension.

If you want to take a stab at a pull request, I'll be happy to review it and merge it. Otherwise, we will not be actively maintaining.
